DROP TABLE IF EXISTS `child_db`.`child_picture` ;
CREATE TABLE child_picture(
	ID CHAR(32) NOT NULL,
	CHILD_ID CHAR(32) NOT NULL,
	FILE_NAME VARCHAR(255) NOT NULL,
	FILE_TYPE VARCHAR(255) NOT NULL,
	FILE_SIZE INT NOT NULL,
	FILE_CONTENT MEDIUMBLOB NOT NULL,
	SORT_ORDER INT(4),
	COMMENT VARCHAR(255) NOT NULL,
	INSERT_USER_ID CHAR(32),
 	UPDATE_USER_ID CHAR(32),
	INSERT_DATETIME DATETIME,
 	UPDATE_DATETIME DATETIME,
 	FOREIGN KEY (CHILD_ID) REFERENCES child(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY(ID)
)ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;