DROP TABLE IF EXISTS `child_db`.`grama_sevaka_division` ;
CREATE TABLE grama_sevaka_division(
	ID CHAR(32) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	CODE VARCHAR(8),
	DIVISIONAL_SECRETARIAT_ID CHAR(32) NOT NULL,
	/*GRAMA_SEVAKA_ID CHAR(32) NOT NULL, */
	SORT_ORDER INT(4),
	INSERT_USER_ID CHAR(32),
 	UPDATE_USER_ID CHAR(32),
	INSERT_DATETIME DATETIME,
 	UPDATE_DATETIME DATETIME,
	PRIMARY KEY(ID),
	FOREIGN KEY (DIVISIONAL_SECRETARIAT_ID) REFERENCES divisional_secretariat(ID) ON UPDATE CASCADE ON DELETE CASCADE
	/*FOREIGN KEY (GRAMA_SEVAKA_ID) REFERENCES grama_sevaka(ID) ON UPDATE RESTRICT ON DELETE CASCADE */
)ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;