DROP TABLE IF EXISTS `child_db`.`monthly_data`;
create table monthly_data(
	
	ID CHAR(32)NOT NULL,
	FILLED_USER_ID CHAR(32) NOT NULL,
	LAMA_NIVASA_ID CHAR(32) NOT NULL,
	UPDATED_DATE DATETIME,
	NUM_OF_CHILDREN INT,
	NUM_OF_OFFICERS INT,
	NUM_OF_VACANT_OFFICERS INT;
	NUM_OF_FEMALE_REUNIFICATOIN INT,
	NUM_OF_MALE_REUNIFICATION INT,
	NUM_OF_FEMALE_TRANSFERS INT,
	NUM_OF_MALE_TRANSFERS INT,
	NUM_OF_PROFORMA_FEMALE INT,
	NUM_OF_PROFORMA_MALE INT
	MALE_HAVING_PRO_FORMA INT,
	NUM_OF_GUARDIANS INT,
	NUM_OF_GUARDIANS INT,
	NUM_FEMALE_TERMINATES INT,
	NUM_OF_MALE_TERMINATES INT,
	NUM_OF_FEMALE_HAVING_SPECIAL_REQUIREMENTS INT,
	MUN_OF_MALE_HAVING_SPECIAL_REQUIREMENTS INT,
	NUM_OF_MEETINGS_UPTO_NOW,
	COUNSELLING _OFFICER_VISITED_DATE DATETIME,
	DEPT_PROBATION_OFFICER_VISITED_DATE DATETIME,
	PROBATION_OFFICER_VISITED_DATE DATETIME,
	DEPARTMENT_COMMISSIONER_VISITED_DATE DATETIME,
	DEPARTMENT_OF_CHILD_DEVELOPMENT_OFFICER_VISITED_DATE DATETIME,
	THE_LAST_MEETING_HELD_ON DATETIME,
	PRIMARY KEY(ID)
)
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;