DROP TABLE IF EXISTS `child_db`.`child_record` ;
CREATE TABLE child_record(
	ID CHAR(32) NOT NULL,
	RECORD_DATE DATETIME NOT NULL,
	COMMENT TEXT,
	CHILD_ID CHAR(32) NOT NULL,
	SORT_ORDER INT(4),
	INSERT_USER_ID CHAR(32),
 	UPDATE_USER_ID CHAR(32),
	INSERT_DATETIME DATETIME,
 	UPDATE_DATETIME DATETIME,
 	FOREIGN KEY (CHILD_ID) REFERENCES child(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY(ID)
)ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;
