DROP TABLE IF EXISTS `child_db`.`generic_list` ;

CREATE TABLE generic_list(
	ID CHAR(32) NOT NULL,
	GENERIC_CATEGORY_ID CHAR(32) NOT NULL,
	LIST_KEY VARCHAR(128) NOT NULL,
	LIST_VALUE VARCHAR(128) NOT NULL,
	SORT_ORDER INT(4),
	INSERT_USER_ID CHAR(32),
 	UPDATE_USER_ID CHAR(32),
	INSERT_DATETIME DATETIME,
 	UPDATE_DATETIME DATETIME,
	PRIMARY KEY(ID),
	FOREIGN KEY (GENERIC_CATEGORY_ID) REFERENCES generic_category(ID) ON UPDATE RESTRICT ON DELETE RESTRICT
)ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;