DROP TABLE IF EXISTS `child_db`.`grama_sevaka` ;
CREATE TABLE grama_sevaka(
	ID CHAR(32) NOT NULL,
	TITLE CHAR(8),
	NAME VARCHAR(255) NOT NULL,
	CONTACT_NUMBER CHAR(16),
	SORT_ORDER INT(4),
	INSERT_USER_ID CHAR(32),
 	UPDATE_USER_ID CHAR(32),
	INSERT_DATETIME DATETIME,
 	UPDATE_DATETIME DATETIME,
	PRIMARY KEY(ID)
)ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;