DROP TABLE IF EXISTS `child_db`.`monthly_data`;
create table monthly_data(
	ID CHAR(32)NOT NULL,--to store report id--
	FILLED_USER_ID CHAR(32) NOT NULL,
	LAMA_NIVASA_ID CHAR(32) NOT NULL,
	UPDATED_DATE DATETIME,
	NUM_OF_CHILDREN INT,
	NUM_OF_OFFICERS INT,
	NUM_OF_VACANT_OFFICERS INT;
	FEMALE_SOCIETALS IN,
	MALE_SOCIETALS INT,
	FEMALE_TRANSFERRED INT,
	MALE_TRANSFERRED INT,
	FEMALE_HAVING_PRO_FORMA INT,
	MALE_HAVING_PRO_FORMA INT,
	FEMALE_HAVING_NO_GUARDIANS INT,
	MALE_HAVING_NO_GUARDIANS INT,
	FEMALE_TERMINATED INT,
	MALE_TERMINATED INT,
	FEMALE_HAVING_SPECIAL_REQUIREMENTS INT,
	MALE_HAVING_SPECIAL_REQUIREMENTS INT,
	NUM_OF_MEETINGS_UPTO_NOW,
	COUNSELLING _OFFICER_VISITED_DATE DATETIME,
	DEPT_PROBATION_OFFICER_VISITED_DATE DATETIME,
	PROBATION_OFFICER_VISITED_DATE DATETIME,
	DEPT_COMMISSIONER_VISITED_DATE DATETIME,
	DEPT_OF_CHILD_DEVELOPMENT_OFFICER_VISITED_DATE DATETIME,
	THE_LAST_MEETING_HELD_ON DATETIME,
	PRIMARY KEY(ID)
)
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;