DROP TABLE IF EXISTS `child_db`.`probation_unit` ;

CREATE TABLE probation_unit(
	ID CHAR(32) NOT NULL,
	NAME CHAR(32) NOT NULL,
	EMAIL CHAR(64),
	NUMBER_OF_OFFICERS INT(3),
	TELEPHONE CHAR(16),
	FAX CHAR(16),
	ADDRESS VARCHAR(255),
	POLICE_STATION_ID CHAR(32),
	COMMENT TEXT,
	SORT_ORDER INT(4),
	INSERT_USER_ID CHAR(32),
 	UPDATE_USER_ID CHAR(32),
	INSERT_DATETIME DATETIME,
 	UPDATE_DATETIME DATETIME,
 	FOREIGN KEY (POLICE_STATION_ID) REFERENCES police_station(ID) ON DELETE SET NULL ON UPDATE CASCADE,
	PRIMARY KEY(ID)
)ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;
